# Site
repository: sinanrk/sinanrk
#favicon: #images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sinan Rasiya Koya
title: PhD Student, University of Nebraska-Lincoln
email: ssinanrk2@huskers.unl.edu
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: rk_sinan
github_username:  sinanrk
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chummavitte
linkedin_username: sinan-rasiya-koya-022844152
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000
googlescholar_username: qrAUhPQAAAAJ

# Additional icon links
# additional_links:
# - title: Google Scholar
#   icon: fa-brands fa-google-scholar
#   url: https://scholar.google.com/citations?user=qrAUhPQAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/ProfilePic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sinan and I'm a PhD student working on ML in Hydrology. 

#I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 2024 - 
          # link: github.com/sproogen
          # link_text: Project Website
          # additional_links:
          #   - title:  sproogen/modern-resume-theme
          #     icon: fab fa-github
          #     url: github.com/sproogen/modern-resume-theme
            # - title:  Github page for project (eg. sproogen/modern-resume-theme)
            #   icon: fab fa-github
            #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
          # quote: >
          #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          > ## Northern Pacific sea-level pressure controls rain-on-snow in North America  
          > *Communications Earth & Environment* | <https://doi.org/10.1038/s43247-024-01431-6>  
          > <br>
          >   This study examines the causal drivers of rain-on-snow (ROS) events in North America, 
          proposing a new ROS identification method and finding a strong link between the North-Pacific Index 
          and ROS frequencies across the continent, offering insights into ROS mechanisms.
          <br>  

           
          > ## Temporal Fusion Transformers for streamflow Prediction: Value of combining attention with recurrence  
          > *Journal of Hydrology* | <https://doi.org/10.1016/j.jhydrol.2024.131301>  
          > <br>
          >   This study employs the Temporal Fusion Transformer (TFT) architecture, combining recurrence and attention mechanisms, 
          and tests its efficacy against LSTM and Transformers using the Caravan dataset. Results show TFT outperforms LSTM and 
          Transformers in streamflow prediction across globally distributed catchments, offering explainable insights into streamflow 
          generation processes.
          <br>  
           
          ***  
      - layout: left
        title: 2023 - 
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          > ## Applicability of a flood forecasting system for Nebraska watersheds  
          > *Environmental Modelling & Software* | <https://doi.org/10.1016/j.envsoft.2023.105693>  
          > <br>
          >   This study developed a flood forecasting system prototype for Nebraska's Elkhorn River basin, 
          incorporating components from the Iowa Flood Information System, including the Hillslope Link Model with 
          enhanced snow process parameterizations, resulting in improved flood peak simulations.
          <br>  

          
          > ## Snow-detonated floods: Assessment of the US midwest March 2019 event  
          > *Journal of Hydrology: Regional Studies* | <https://doi.org/10.1016/j.ejrh.2023.101387>  
          > <br>
          >   The study analyzes the unexpected major snow-related flood in March 2019 caused by a meteorological bomb cyclone, 
          assesses early-spring peak flow trends, explores a parsimonious hydrological model with a snow component, 
          and validates the model's performance over the last 20 years
          <br>  
          
          > ## An autoencoder-based snow drought index    
          > *Scientific Reports* | <https://doi.org/10.1038/s41598-023-47999-5>  
          > <br>
          >   The study introduces the Snow Drought Response Index (SnoDRI), a novel indicator designed to efficiently identify 
          and quantify snow drought occurrences, particularly in regions where snow significantly impacts hydrology, such as the 
          western United States. Utilizing cutting-edge machine learning algorithms, including self-supervised learning of autoencoders 
          combined with mutual information, the index is calculated from various snow-related variables.  

          
          ***  

          
      - layout: left
        title: 2022 -
  #       # link: github.com/sproogen
  # #       # link_text: Project Website
  # #       additional_links:
  # #         - title:  sproogen/modern-resume-theme
  # #           icon: fab fa-github
  # #           url: github.com/sproogen/modern-resume-theme
  # #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  # #         #   icon: fab fa-github
  # #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  # #       quote: >
  # #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          > ## The great lakes runoff intercomparison project phase 4: the great lakes (GRIP-GL)  
          > *Hydrology and Earth System Sciences* | <https://doi.org/10.5194/hess-26-3537-2022>  
          > <br>
          >   Model intercomparison studies evaluate various models over the Great Lakes region. 
          This study involved 13 diverse models, using standardized setups to compare their performance in simulating streamflow, actual evapotranspiration, surface soil moisture, and snow water equivalent.  

          > ## Application of Neural Networks for Hydrologic Process Understanding at a Midwestern Watershed  
          > *Hydrology* | <https://doi.org/10.3390/hydrology10020027>  
          > <br>
          >   This study investigates the impact of conservation practices on flood mitigation in the Shell Creek Watershed (SCW), 
          Nebraska, using an artificial neural network (ANN)-based rainfall-runoff model. Thirteen controlling factors were analyzed, 
          alongside flood frequency and drought severity.
          

  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: 
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Nebraska-Lincoln
        caption: 2021 - Present
        sub_title: PhD Civil Engineering (Water Resources)
        # quote: >
        #   Established in 18xx. More history about the dept. 
        description: | # this will include new lines to allow paragraphs
          Research is the main thing. Some badminton too.
      - layout: left
        title: Indian Institude of Technology, Gandhinagar
        caption: 2016 - 2020
        sub_title: Bachelor of Technology, Civil Engineering
        # quote: >
        #   Established in 18xx. More history about the dept. 
        description: | # this will include new lines to allow paragraphs
          Pitching time. Had fun playing football (I mean soccer)

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sinanrk/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
