# Site
repository: sinanrk/sinanrk
#favicon: #images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sinan Rasiya Koya
title: PhD Student, University of Nebraska-Lincoln
email: ssinanrk2@huskers.unl.edu
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: rk_sinan
github_username:  sinanrk
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chummavitte
linkedin_username: sinan-rasiya-koya-022844152
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000
googlescholar_username: qrAUhPQAAAAJ

# Additional icon links
# additional_links:
# - title: Google Scholar
#   icon: fa-brands fa-google-scholar
#   url: https://scholar.google.com/citations?user=qrAUhPQAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/ProfilePic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sinan and I'm a PhD student working on ML in Hydrology. 

#I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 2023 - 
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Applicability of a flood forecasting system for Nebraska watersheds  
          *Environmental Modelling & Software* | <https://doi.org/10.1016/j.envsoft.2023.105693>
          .. Some description
          
          Snow-detonated floods: Assessment of the US midwest March 2019 event  
          *Journal of Hydrology: Regional Studies* | <https://doi.org/10.1016/j.ejrh.2023.101387>
          ## Some description
          
          An autoencoder-based snow drought index    
          *Scientific Reports* | <https://doi.org/10.1038/s41598-023-47999-5>
          ...Some description
          
          ***
      - layout: left
        title: 2022 -
  #       # link: github.com/sproogen
  # #       # link_text: Project Website
  # #       additional_links:
  # #         - title:  sproogen/modern-resume-theme
  # #           icon: fab fa-github
  # #           url: github.com/sproogen/modern-resume-theme
  # #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  # #         #   icon: fab fa-github
  # #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  # #       quote: >
  # #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          The great lakes runoff intercomparison project phase 4: the great lakes (GRIP-GL)
          Hydrology and Earth System Sciences | <https://doi.org/10.5194/hess-26-3537-2022>
          
          ***
  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: 
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Nebraska-Lincoln
        caption: 2021 - Present
        sub_title: PhD Civil Engineering (Water Resources)
        # quote: >
        #   Established in 18xx. More history about the dept. 
        description: | # this will include new lines to allow paragraphs
          Research is the main thing. Some badminton too.
      - layout: left
        title: Indian Institude of Technology, Gandhinagar
        caption: 2016 - 2020
        sub_title: Bachelor of Technology, Civil Engineering
        # quote: >
        #   Established in 18xx. More history about the dept. 
        description: | # this will include new lines to allow paragraphs
          Pitching time. Had fun playing football (I mean soccer)

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sinanrk/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
